<a href="https://colab.research.google.com/github/Mrkomiljon/google-colab-/blob/main/model1_to_model2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import missingno as msno
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
# from catboost import CatBoostClassifier
from sklearn import metrics
from sklearn.metrics import roc_curve
from sklearn.metrics import recall_score, confusion_matrix, precision_score, f1_score, accuracy_score, classification_report

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/Mrkomiljon/google-colab-/main/churn_dataset.csv')
df.sample(5)

Gender  Senior Citizen  Partner  Dependents  Tenure Months  \
1533       0               0        1           0       0.225352   
1908       1               1        1           0       0.915493   
2599       0               0        0           0       0.154930   
6576       0               1        0           0       0.873239   
26         0               1        1           1       0.507042   

      Phone Service  Monthly Charges  Total_Charges  Churn Value  \
1533              1         0.668657       0.165336            1   
1908              1         0.897512       0.814395            0   
2599              1         0.254229       0.060253            0   
6576              1         0.644279       0.602844            0   
26                1         0.579602       0.328796            1   

      Internet Service_0  ...  Streaming Movies_2  Contract_0  Contract_1  \
1533                   0  ...                   1           1           0   
1908                   0  ...                   1           0           1   
2599                   1  ...                   0           1           0   
6576                   1  ...                   0           0           1   
26                     0  ...                   0           1           0   

      Contract_2  Paperless Billing_0  Paperless Billing_1  Payment Method_0  \
1533           0                    0                    1                 0   
1908           0                    0                    1                 0   
2599           0                    1                    0                 1   
6576           0                    1                    0                 1   
26             0                    0                    1                 0   

      Payment Method_1  Payment Method_2  Payment Method_3  
1533                 0                 1                 0  
1908                 0                 1                 0  
2599                 0                 0                 0  
6576                 0                 0                 0  
26                   0                 1                 0  

[5 rows x 42 columns]

In [ ]:
X = df.drop(columns = ['Churn Value'])
y = df['Churn Value'].values

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3, random_state = 42, stratify=y)

In [ ]:
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train,y_train)
predictdt_y = dt_model.predict(X_test)
accuracy_dt = dt_model.score(X_test,y_test)
print("Decision Tree accuracy is :",accuracy_dt)
print(confusion_matrix(y_test,predictdt_y))
print(classification_report(y_test,predictdt_y))

Decision Tree accuracy is : 0.7327014218009479
[[1277  272]
 [ 292  269]]
              precision    recall  f1-score   support

           0       0.81      0.82      0.82      1549
           1       0.50      0.48      0.49       561

    accuracy                           0.73      2110
   macro avg       0.66      0.65      0.65      2110
weighted avg       0.73      0.73      0.73      2110



In [ ]:
print(classification_report(y_test, predictdt_y))

              precision    recall  f1-score   support

           0       0.81      0.82      0.82      1549
           1       0.50      0.48      0.49       561

    accuracy                           0.73      2110
   macro avg       0.66      0.65      0.65      2110
weighted avg       0.73      0.73      0.73      2110



In [ ]:
from sklearn.svm import SVC
svm=SVC()
#Fit the model to the training dataset
svm.fit(X_train,y_train)
#Predict using the test set
predictions=svm.predict(X_test)
#instantiate Evaluation matrics
from sklearn.metrics import classification_report,confusion_matrix
print("SVM", accuracy_score(y_test, predictions))
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

SVM 0.804739336492891
[[1387  162]
 [ 250  311]]
              precision    recall  f1-score   support

           0       0.85      0.90      0.87      1549
           1       0.66      0.55      0.60       561

    accuracy                           0.80      2110
   macro avg       0.75      0.72      0.74      2110
weighted avg       0.80      0.80      0.80      2110



In [ ]:
gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)
gb_pred = gb.predict(X_test)
gb_pred_train = gb.predict(X_train)

print("Gradient Boosting Classifier", accuracy_score(y_test, gb_pred))
print(confusion_matrix(y_test,gb_pred))
print(classification_report(y_test,gb_pred))

Gradient Boosting Classifier 0.8009478672985783
[[1379  170]
 [ 250  311]]
              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1549
           1       0.65      0.55      0.60       561

    accuracy                           0.80      2110
   macro avg       0.75      0.72      0.73      2110
weighted avg       0.79      0.80      0.80      2110



In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
#Fit the model to the training set and predict using the test set
lr.fit(X_train,y_train)
predictions=lr.predict(X_test)
#Evaluation matrics
print("LR", accuracy_score(y_test, predictions))
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

LR 0.8071090047393364
[[1367  182]
 [ 225  336]]
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      1549
           1       0.65      0.60      0.62       561

    accuracy                           0.81      2110
   macro avg       0.75      0.74      0.75      2110
weighted avg       0.80      0.81      0.80      2110



In [ ]:
'Churn Value' in X_train

False

In [ ]:
models    = [ gb , svm, lr, dt_model]

for i in models:
  for j in models : 
    if  i!=j:
      i.fit(X_train, y_train)
      X_train['model1_out'] = i.predict(X_train)
      X_test['model1_out'] = i.predict(X_test)
     # print('model 1  accuracy .... ', i.accuracy_score )
      new_data = X_test.append(X_train) 
      #X = new_data.drop(columns = ['Churn Value'])
      #y = df['Churn Value'].values
      X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size = 0.3, random_state = 42, stratify=y)
      j.fit(X_train1, y_train1) 
      last_out_train = j.predict(X_train1)
      last_out_test = j.predict(X_test1)
      #print(f'acc of joined model: {j.accuracy_score}' )
      # new_datay =  y_test.append(y_train) 

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
#Fit the model to the training set and predict using the test set
lr.fit(X_train1,y_train1)
predictions1=lr.predict(X_test1)
#Evaluation matrics
print("LR", accuracy_score(y_test, predictions1))
print(confusion_matrix(y_test,predictions1))
print(classification_report(y_test,predictions1))

LR 0.8071090047393364
[[1367  182]
 [ 225  336]]
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      1549
           1       0.65      0.60      0.62       561

    accuracy                           0.81      2110
   macro avg       0.75      0.74      0.75      2110
weighted avg       0.80      0.81      0.80      2110



In [ ]:
'Churn Value' in new_data

False

In [ ]:
gb = GradientBoostingClassifier()
gb.fit(X_train1, y_train1)
gb_pred1 = gb.predict(X_test1)
gb_pred_train1 = gb.predict(X_train1)

print("Gradient Boosting Classifier", accuracy_score(y_test, gb_pred1))
print(confusion_matrix(y_test,gb_pred1))
print(classification_report(y_test,gb_pred1))

Gradient Boosting Classifier 0.8009478672985783
[[1379  170]
 [ 250  311]]
              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1549
           1       0.65      0.55      0.60       561

    accuracy                           0.80      2110
   macro avg       0.75      0.72      0.73      2110
weighted avg       0.79      0.80      0.80      2110

