<a href="https://colab.research.google.com/github/Mrkomiljon/google-colab-/blob/main/numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
my_list= list(range(100000))
my_list2= np.array(range(100000))

In [3]:
%time for _ in range(10): [x*2 for x in my_list]

CPU times: user 77.5 ms, sys: 11.9 ms, total: 89.4 ms
Wall time: 90.6 ms


In [4]:
%time for _ in range(10): my_list2*2

CPU times: user 3.58 ms, sys: 0 ns, total: 3.58 ms
Wall time: 8.43 ms


In [5]:
89/3

29.666666666666668

In [7]:
data1=[3, 5, 9, 3.5]
arr1=np.array(data1)

In [8]:
arr1

array([3. , 5. , 9. , 3.5])

In [9]:
data3=[[1, 2, 3, 4], [5, 6, 7, 8]]
arr3= np.array(data3)

In [10]:
arr3

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
data4=[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr4= np.array(data4)

In [12]:
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
arr4.ndim

2

In [14]:
arr4.searchsorted

<function ndarray.searchsorted>

In [15]:
arr4.shape

(3, 4)

In [16]:
arr4.size

12

In [19]:
arr5=np.zeros(shape=(2,4))
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
arr6= np.arange(2, 20, 2)
arr6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])