<a href="https://colab.research.google.com/github/Mrkomiljon/google-colab-/blob/main/pracrice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a= np.random.rand(3,2,4)
a

array([[[0.33682604, 0.74437312, 0.90907047, 0.82975401],
        [0.74966208, 0.08131128, 0.22209935, 0.52902661]],

       [[0.4369032 , 0.64210129, 0.72446303, 0.54617162],
        [0.09320205, 0.87660551, 0.42723873, 0.19432072]],

       [[0.73637378, 0.03965466, 0.85694555, 0.06134922],
        [0.43039092, 0.69205559, 0.76132447, 0.03035494]]])

In [4]:
a.size

24

In [5]:
a.shape

(3, 2, 4)

In [6]:
a.ndim

3

In [7]:
a.dtype

dtype('float64')

In [9]:
b= np.arange(6)
b

array([0, 1, 2, 3, 4, 5])

In [10]:
b.ndim

1

In [11]:
# 1d -> 2d
c= np.reshape(b, (2, 3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
c.ndim

2

In [13]:
#2d -> 3d
d=np.reshape(c, c.shape + (1,))
d

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]]])

In [15]:
d.ndim

3

In [16]:
#3d -> 2d
e= np.reshape(d, (2, 3))
e

array([[0, 1, 2],
       [3, 4, 5]])

In [17]:
e=np.reshape(d, (3, 2))
e

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
e.ndim

2

In [19]:
#2d -> 1d
f= np.reshape(e, (6))
f

array([0, 1, 2, 3, 4, 5])

In [20]:
f.ndim

1

In [22]:
a=np.array([[1, 2], [3, 4]])
a.flatten() # bir tekis chiqaradi

array([1, 2, 3, 4])

In [23]:
a.flatten('F')

array([1, 3, 2, 4])

In [24]:
x= np.arange(1, 7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
x.flat[3]

4

In [26]:
x.flat[1]

2

In [27]:
len(a)

2

In [28]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
k=np.reshape(x, (6))
k

array([1, 2, 3, 4, 5, 6])

In [31]:
k[1::2] # :: 2 bu ikkita indeks [interval] siljitish uchun ishlatiladi

array([2, 4, 6])

In [32]:
k[-4::2]

array([3, 5])

In [33]:
k[3:]

array([4, 5, 6])

In [34]:
y= np.arange(42).reshape(7, 6)
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [35]:
y.ndim

2

In [37]:
l=np.reshape(y, y.shape +(1,))
l

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15],
        [16],
        [17]],

       [[18],
        [19],
        [20],
        [21],
        [22],
        [23]],

       [[24],
        [25],
        [26],
        [27],
        [28],
        [29]],

       [[30],
        [31],
        [32],
        [33],
        [34],
        [35]],

       [[36],
        [37],
        [38],
        [39],
        [40],
        [41]]])

In [38]:
l.ndim

3

In [39]:
l[0]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [40]:
l[1]

array([[ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [41]:
y[0]

array([0, 1, 2, 3, 4, 5])

In [42]:
y[6][1:4]

array([37, 38, 39])

In [43]:
y[6]

array([36, 37, 38, 39, 40, 41])

In [46]:
y[6][-1]

41

In [47]:
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [48]:
y[:,3]

array([ 3,  9, 15, 21, 27, 33, 39])

In [50]:
y[:, 0]

array([ 0,  6, 12, 18, 24, 30, 36])

In [57]:
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [58]:
# massivni qirqib olish
y[2, 3]

15

In [59]:
y[5, 4]

34

In [60]:
y[0:3, 5]     # 0:3 row and 5 column

array([ 5, 11, 17])

In [61]:
y[1:4, 0:2]

array([[ 6,  7],
       [12, 13],
       [18, 19]])

In [62]:
y[2:5, 2:5]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

In [63]:
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [64]:
y[0::2, 0:]   #qatorni 2 interval bn tashlash va 0chi indeksdan oxirigacha column

array([[ 0,  1,  2,  3,  4,  5],
       [12, 13, 14, 15, 16, 17],
       [24, 25, 26, 27, 28, 29],
       [36, 37, 38, 39, 40, 41]])

In [65]:
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [66]:
y[:, 0::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28],
       [30, 32, 34],
       [36, 38, 40]])

In [67]:
y

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41]])

In [68]:
y[1::2, 1::2]

array([[ 7,  9, 11],
       [19, 21, 23],
       [31, 33, 35]])

In [70]:
q=np.arange(45).reshape(3, 3, 5)
q

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [71]:
q[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [75]:
q[1:]

array([[[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44]]])

In [78]:
q[1:, 0:1]

array([[[15, 16, 17, 18, 19]],

       [[30, 31, 32, 33, 34]]])

In [79]:
q[1:, 0:2, 1:4]

array([[[16, 17, 18],
        [21, 22, 23]],

       [[31, 32, 33],
        [36, 37, 38]]])