<a href="https://colab.research.google.com/github/Mrkomiljon/google-colab-/blob/main/vazifa(2_1_2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Faqatgina `YOUR CODE HERE` yoki "YOUR ANSWER HERE" deyilgan joyga dasturingizni yoki javobingizni yozing

In [ ]:
NAME = "Mukhammadiev Komiljon"
COLLABORATORS = "Mohirdev"

---

---
# Ma'lumotlar tahlili

## 2.1.1. N-O'lchovli massivlarga ishlov berish

## Vazifa-2

In [ ]:
# Numpy kutubxonasini chaqirib olish
import numpy as np

### Masala(1): 2-o'lchamli massiv yaratish (1 point)

**Masala sharti :** Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv yarating. 

**Yordam :**  `arange`dan foydalanish ishni osonlashtiradi 


In [ ]:
def nd_array():
    """Elementlari 0 dan 9 gacha (9 ning o'zi massiv elementiga kirmaydi), qadami esa 1 ga teng bo'lgan (3, 3) o'lchamli massiv """
    # YOUR CODE HERE
    return np.arange(9).reshape(3, 3)
   
    raise NotImplementedError()

In [ ]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Sizning funksiyangiz massiv elementlari soni, `shape` massiv shakli, hamda elementlari 0~10 oralig'idagi numpy array ekanligi orqali tekshiriladi. Bundan tashqari bir qancha maxfiy testlardan o'tkaziladi (maslahatimiz aldashga urinmang). 

In [ ]:
"""Funksiyani tekshirish"""
arr = nd_array() # massiv
assert arr.size == 9  # elementlar soni
assert type(arr) == np.ndarray # #numpy array 

###  Masala(2): Indeks yordamida 2-o'lchamli massivlardan elementlarni  kesib olish (3 points)

**Masala :** Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasini tuzing.

**Yordam :** 6 va 7 turgan indekslarni aniqlab olib, shu indekslar yordamida kesib oling. **Natija:** array([6, 7]) ko'rinishida bo'lishi kerak. 

In [ ]:
def sliced_array_2d():
    """Yuqorida yaratilgan massivning elementlari 6 va 7 ga teng bo'lgan qismini kesib olish funksiyasi """
    # YOUR CODE HERE
    a=np.arange(9).reshape(3, 3)
    return a[2:, 0:2]
    raise NotImplementedError()

In [ ]:
a=np.arange(9).reshape(3, 3)
a[2:, 0:2]

array([[6, 7]])

Sizning funksiyangiz massiv elementlari soni, `shape` massiv shakli, hamda elementlari numpy array ekanligi orqali tekshiriladi. Bundan tashqari bir qancha maxfiy testlardan o'tkaziladi (maslahatimiz aldashga urinmang). 

In [ ]:
"""Funksiyani tekshirish"""
sl_arr_2d = sliced_array_2d() # kesib olingan massiv
# assert sl_arr_2d.size == 9  # elementlar soni
assert type(sl_arr_2d) == np.ndarray # #numpy array 

###  Masala(3): Indeks yordamida 3-o'lchamli massivdan elementlarni kesib olish (4 points)

**Masala :**  3-o'lchamli massivni quyidagi listdan yarating, hamda 12, 13, 15, va 16  elementlarini kesib oling. 

                  [[[ 0,  1,  2],
                    [ 3,  4,  5],
                    [ 6,  7,  8]],

                   [[ 9, 10, 11],
                    [12, 13, 14],
                    [15, 16, 17]],

                   [[18, 19, 20],
                    [21, 22, 23],
                    [24, 25, 26]]]

**Yordam :** Avval massivni ikki o'lchamli massivga keltirib, keyin kesib olishni amalga oshiring. 


**Natija:**  

             array([[12, 13],
                    [15, 16]])
ko'rinishida bo'lishi kerak. 

Sizning funksiyangiz massiv elementlari soni, `shape` massiv shakli, hamda elementlari numpy array ekanligi orqali tekshiriladi. Bundan tashqari bir qancha maxfiy testlardan o'tkaziladi (maslahatimiz aldashga urinmang). 

In [ ]:
def sliced_array_3d():
    """3-o'lchamli massivni yuqoridagi listdan yaratish, hamda 12, 13, 15, va 16 elementlarini kesib olish funksiyasi"""
    # YOUR CODE HERE
    q=np.arange(27).reshape(3, 3, 3)
    return q[1][0:3, 0:2]
    raise NotImplementedError()

In [ ]:
q=np.arange(27).reshape(3, 3, 3)
q

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
q[1][1:3, 0:2]

array([[12, 13],
       [15, 16]])

In [ ]:
q.size

27

In [ ]:
type(q)

numpy.ndarray

In [ ]:
"""Funksiyani tekshirish"""
sl_arr_3d = sliced_array_3d() # kesib olingan massiv
# assert sl_arr_3d.size == 27  # elementlar soni
assert type(sl_arr_3d) == np.ndarray # #numpy array 

###  Masala(4): Boolean indeks yordamida 2-o'lchamli massivlardan elementlarni  kesib olish (2 points)

**Masala :** Bizlarda,  
        
        ['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor']

**list**dagi kishilar va ularning **ma'lumot**lari 
       
      [[5, 6, 1, 1],
       [9, 1, 1, 1],
       [7, 7, 4, 2],
       [1, 5, 1, 9],
       [9, 9, 4, 5],
       [7, 5, 9, 6],
       [5, 3, 7, 4]]
ko'rinishda keltirilgan. 


Mana shu ma'lumotlardan **Javohir** va **Elyor** ismlariga tegishli ma'lumotlarni Boolean indekslash yordamida kesib olish funksiyasini tuzing. 
**Yordam :** Boolean indekslash video darsligiga murojat qiling. **Natija:** Natija (4, 4) o'lchamli massiv ko'rinishida, hamda dastlabki ikkita qattori quyidagicha

    array([[7, 7, 4, 2],
           [1, 5, 1, 9],
           ...
           ...        ]])

In [ ]:
names= np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
names

array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'],
      dtype='<U7')

In [ ]:
data= np.array( [[5, 6, 1, 1],
   [9, 1, 1, 1],
   [7, 7, 4, 2],
   [1, 5, 1, 9],
   [9, 9, 4, 5],
   [7, 5, 9, 6],
   [5, 3, 7, 4]])
data

array([[5, 6, 1, 1],
       [9, 1, 1, 1],
       [7, 7, 4, 2],
       [1, 5, 1, 9],
       [9, 9, 4, 5],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])

In [ ]:
data

array([[5, 6, 1, 1],
       [9, 1, 1, 1],
       [7, 7, 4, 2],
       [1, 5, 1, 9],
       [9, 9, 4, 5],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])

In [ ]:
print(names)
print(data)

['Hasan' 'Husan' 'Javohir' 'Elyor' 'Hasan' 'Javohir' 'Elyor']
[[5 6 1 1]
 [9 1 1 1]
 [7 7 4 2]
 [1 5 1 9]
 [9 9 4 5]
 [7 5 9 6]
 [5 3 7 4]]


In [ ]:
names =='Hasan'

array([ True, False, False, False,  True, False, False])

In [ ]:
mask = (names == 'Javohir') | (names == 'Elyor')
mask

array([False, False,  True,  True, False,  True,  True])

In [ ]:
data[mask].size

16

In [ ]:
data[mask]

array([[7, 7, 4, 2],
       [1, 5, 1, 9],
       [7, 5, 9, 6],
       [5, 3, 7, 4]])

In [ ]:
def boolean_slicing():
    """Boolean indekslash yordamida ma'lumotlarni kesib olish """
    # YOUR CODE HERE
    names= np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
    data= np.array( [[5, 6, 1, 1],
                    [9, 1, 1, 1],
                    [7, 7, 4, 2],
                    [1, 5, 1, 9],
                    [9, 9, 4, 5],
                    [7, 5, 9, 6],
                    [5, 3, 7, 4]])
    
    return data[(names == 'Javohir') | (names == 'Elyor')] 
  #    raise NotImplementedError()

Sizning funksiyangiz massiv elementlari soni, `shape` massiv shakli, hamda elementlari numpy array ekanligi orqali tekshiriladi. Bundan tashqari bir qancha maxfiy testlardan o'tkaziladi (maslahatimiz aldashga urinmang). 

In [ ]:

"""Funksiyani tekshirish"""
bool_idx = boolean_slicing() # kesib olingan massiv
assert bool_idx.size == 16  # elementlar soni
assert type(bool_idx) == np.ndarray # #numpy array 